import { createSlice } from "@reduxjs/toolkit";

/**
 * Initial state of the employees slice.
 * @typedef {Object} EmployeesState
 * @property {Array<Object>} employees - An array of employee objects.
 */
/**
 * An employee object.
 * @typedef {Object} Employee
 * @property {string} firstName - The first name of the employee.
 * @property {string} lastName - The last name of the employee.
 * @property {string} dateOfBirth - The date of birth of the employee (in YYYY-MM-DD format).
 * @property {string} startDate - The start date of the employee (in YYYY-MM-DD format).
 * @property {string} street - The street address of the employee.
 * @property {string} city - The city of the employee.
 * @property {string} state - The state of the employee.
 * @property {string} zipCode - The ZIP code of the employee.
 * @property {string} department - The department of the employee.
 * @property {number} id - The unique identifier of the employee.
 */
/**
 * The initial state of the employees slice.
 * @type {EmployeesState}
 */
const initialState = {
  employees: [
    {
      firstName: "Emily",
      lastName: "Brown",
      dateOfBirth: "1991-08-27",
      startDate: "2022-02-15",
      street: "987 Pine Street",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
      department: "Human Resources",
      id: 26,
    },
    {
      firstName: "Michael",
      lastName: "Wilson",
      dateOfBirth: "1988-04-12",
      startDate: "2023-01-05",
      street: "654 Cedar Avenue",
      city: "San Francisco",
      state: "CA",
      zipCode: "94101",
      department: "Engineering",
      id: 27,
    },
    {
      firstName: "Sophia",
      lastName: "Jones",
      dateOfBirth: "1993-12-05",
      startDate: "2022-09-10",
      street: "321 Oakwood Drive",
      city: "Boston",
      state: "MA",
      zipCode: "02101",
      department: "Operations",
      id: 28,
    },
    {
      firstName: "Daniel",
      lastName: "Taylor",
      dateOfBirth: "1987-03-18",
      startDate: "2021-11-20",
      street: "789 Elm Street",
      city: "Denver",
      state: "CO",
      zipCode: "80201",
      department: "Sales",
      id: 29,
    },
    {
      firstName: "Olivia",
      lastName: "Thomas",
      dateOfBirth: "1994-06-30",
      startDate: "2023-04-02",
      street: "456 Maple Avenue",
      city: "Austin",
      state: "TX",
      zipCode: "73301",
      department: "Marketing",
      id: 30,
    },
    {
      firstName: "William",
      lastName: "James",
      dateOfBirth: "1984-04-01",
      startDate: "2022-04-02",
      street: "Park Avenue",
      city: "Los Angeles",
      state: "AL",
      zipCode: "88000",
      department: "Marketing",
      id: 31,
    },
    {
      firstName: "Emily",
      lastName: "Brown",
      dateOfBirth: "1991-08-27",
      startDate: "2022-02-15",
      street: "987 Pine Street",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
      department: "Human Resources",
      id: 32,
    },
    {
      firstName: "Michael",
      lastName: "Johnson",
      dateOfBirth: "1985-04-12",
      startDate: "2021-09-01",
      street: "123 Oak Avenue",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
      department: "Engineering",
      id: 33,
    },
    {
      firstName: "Sophia",
      lastName: "Smith",
      dateOfBirth: "1993-11-15",
      startDate: "2022-06-10",
      street: "789 Maple Street",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
      department: "Marketing",
      id: 34,
    },
    {
      firstName: "Olivia",
      lastName: "Wilson",
      dateOfBirth: "1990-12-03",
      startDate: "2022-05-20",
      street: "456 Elm Street",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      department: "Sales",
      id: 35,
    },
    {
      firstName: "John",
      lastName: "Watson",
      dateOfBirth: "1992-12-03",
      startDate: "2021-07-20",
      street: "50 Washingtown Street",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      department: "Marketing",
      id: 36,
    },
    {
      firstName: "Bob",
      lastName: "Singer",
      dateOfBirth: "1942-12-03",
      startDate: "2020-07-25",
      street: "25 Washingtown Street",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      department: "Sales",
      id: 37,
    },
    {
      firstName: "Dean",
      lastName: "Winchester",
      dateOfBirth: "1979-24-01",
      startDate: "2022-01-01",
      street: "On his impala",
      city: "Houston",
      state: "TX",
      zipCode: "77001",
      department: "Engineering",
      id: 38,
    },
    {
      firstName: "Sam",
      lastName: "Winchester",
      dateOfBirth: "1983-05-02",
      startDate: "2023-01-20",
      street: "On his impala",
      city: "Houston",
      state: "TX",
      zipCode: "77001",
      department: "Sales",
      id: 39,
    },
    {
      firstName: "John",
      lastName: "Doe",
      dateOfBirth: "1990-06-15",
      startDate: "2022-05-10",
      street: "123 Main Street",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
      department: "Marketing",
      id: 40,
    },
    {
      firstName: "Alice",
      lastName: "Smith",
      dateOfBirth: "1985-03-12",
      startDate: "2021-09-15",
      street: "456 Elm Street",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
      department: "HR",
      id: 41,
    },
    {
      firstName: "John",
      lastName: "Johnson",
      dateOfBirth: "1992-11-05",
      startDate: "2022-03-01",
      street: "789 Oak Avenue",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
      department: "Finance",
      id: 42,
    },
    {
      firstName: "Emily",
      lastName: "Davis",
      dateOfBirth: "1988-09-18",
      startDate: "2022-07-05",
      street: "321 Pine Street",
      city: "Miami",
      state: "FL",
      zipCode: "33101",
      department: "Sales",
      id: 43,
    },
    {
      firstName: "Michael",
      lastName: "Wilson",
      dateOfBirth: "1991-04-29",
      startDate: "2022-08-15",
      street: "555 Maple Avenue",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
      department: "Engineering",
      id: 44,
    },
    {
      firstName: "Olivia",
      lastName: "Thompson",
      dateOfBirth: "1994-12-07",
      startDate: "2022-09-20",
      street: "777 Oak Street",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85001",
      department: "Marketing",
      id: 45,
    },
    {
      firstName: "Daniel",
      lastName: "Harris",
      dateOfBirth: "1990-03-22",
      startDate: "2022-10-10",
      street: "999 Elm Avenue",
      city: "Denver",
      state: "CO",
      zipCode: "80201",
      department: "Finance",
      id: 46,
    },
    {
      firstName: "Sophia",
      lastName: "Clark",
      dateOfBirth: "1987-08-14",
      startDate: "2022-11-05",
      street: "111 Pine Street",
      city: "San Francisco",
      state: "CA",
      zipCode: "94101",
      department: "HR",
      id: 47,
    },
    {
      firstName: "William",
      lastName: "Walker",
      dateOfBirth: "1993-06-01",
      startDate: "2022-12-01",
      street: "222 Oak Avenue",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
      department: "Engineering",
      id: 48,
    },
    {
      firstName: "Ava",
      lastName: "Parker",
      dateOfBirth: "1989-01-25",
      startDate: "2023-01-15",
      street: "333 Maple Street",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
      department: "Sales",
      id: 49,
    },
    {
      firstName: "James",
      lastName: "Cook",
      dateOfBirth: "1992-07-10",
      startDate: "2023-02-20",
      street: "444 Elm Avenue",
      city: "Houston",
      state: "TX",
      zipCode: "77001",
      department: "Marketing",
      id: 50,
    },
    {
      firstName: "Liam",
      lastName: "Smith",
      dateOfBirth: "1990-11-12",
      startDate: "2023-03-10",
      street: "555 Pine Street",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      department: "Sales",
      id: 51,
    },
    {
      firstName: "Isabella",
      lastName: "Baker",
      dateOfBirth: "1988-07-25",
      startDate: "2023-04-05",
      street: "777 Oak Avenue",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
      department: "Engineering",
      id: 52,
    },
    {
      firstName: "Benjamin",
      lastName: "Johnson",
      dateOfBirth: "1993-02-18",
      startDate: "2023-05-01",
      street: "999 Elm Street",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
      department: "Finance",
      id: 53,
    },
    {
      firstName: "Mia",
      lastName: "Miller",
      dateOfBirth: "1991-05-08",
      startDate: "2023-06-15",
      street: "111 Maple Avenue",
      city: "Houston",
      state: "TX",
      zipCode: "77001",
      department: "HR",
      id: 54,
    },
    {
      firstName: "Henry",
      lastName: "Davis",
      dateOfBirth: "1995-09-30",
      startDate: "2023-07-20",
      street: "222 Pine Street",
      city: "San Francisco",
      state: "CA",
      zipCode: "94101",
      department: "Engineering",
      id: 55,
    },
    {
      firstName: "Charlotte",
      lastName: "Wilson",
      dateOfBirth: "1992-12-28",
      startDate: "2023-08-10",
      street: "333 Oak Avenue",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
      department: "Sales",
      id: 56,
    },
    {
      firstName: "Alexander",
      lastName: "Taylor",
      dateOfBirth: "1994-04-17",
      startDate: "2023-09-15",
      street: "444 Maple Street",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85001",
      department: "Marketing",
      id: 57,
    },
    {
      firstName: "Sofia",
      lastName: "Anderson",
      dateOfBirth: "1990-08-22",
      startDate: "2023-10-05",
      street: "555 Elm Avenue",
      city: "Denver",
      state: "CO",
      zipCode: "80201",
      department: "Finance",
      id: 58,
    },
    {
      firstName: "James",
      lastName: "Thomas",
      dateOfBirth: "1987-03-15",
      startDate: "2023-11-01",
      street: "777 Pine Street",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
      department: "HR",
      id: 59,
    },
    {
      firstName: "Amelia",
      lastName: "Hernandez",
      dateOfBirth: "1993-01-06",
      startDate: "2023-12-15",
      street: "999 Oak Avenue",
      city: "Miami",
      state: "FL",
      zipCode: "33101",
      department: "Engineering",
      id: 60,
    },
    {
      firstName: "Daniel",
      lastName: "Garcia",
      dateOfBirth: "1989-06-20",
      startDate: "2024-01-20",
      street: "111 Maple Street",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
      department: "Sales",
      id: 61,
    },
    {
      firstName: "Elizabeth",
      lastName: "Martinez",
      dateOfBirth: "1992-02-03",
      startDate: "2024-02-10",
      street: "222 Elm Avenue",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
      department: "Marketing",
      id: 62,
    },
    {
      firstName: "Henry",
      lastName: "Lopez",
      dateOfBirth: "1991-07-12",
      startDate: "2024-03-15",
      street: "333 Pine Street",
      city: "Houston",
      state: "TX",
      zipCode: "77001",
      department: "Finance",
      id: 63,
    },
    {
      firstName: "Scarlett",
      lastName: "Young",
      dateOfBirth: "1995-12-25",
      startDate: "2024-04-05",
      street: "444 Oak Avenue",
      city: "San Francisco",
      state: "CA",
      zipCode: "94101",
      department: "HR",
      id: 64,
    },
    {
      firstName: "Joseph",
      lastName: "Lee",
      dateOfBirth: "1993-03-09",
      startDate: "2024-05-10",
      street: "555 Maple Street",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
      department: "Engineering",
      id: 65,
    },
    {
      firstName: "Victoria",
      lastName: "Walker",
      dateOfBirth: "1988-09-14",
      startDate: "2024-06-15",
      street: "777 Elm Avenue",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85001",
      department: "Sales",
      id: 66,
    },
    {
      firstName: "Andrew",
      lastName: "Lewis",
      dateOfBirth: "1994-05-19",
      startDate: "2024-07-20",
      street: "999 Pine Street",
      city: "Denver",
      state: "CO",
      zipCode: "80201",
      department: "Marketing",
      id: 67,
    },
    {
      firstName: "Grace",
      lastName: "Green",
      dateOfBirth: "1990-10-02",
      startDate: "2024-08-10",
      street: "111 Oak Avenue",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
      department: "Finance",
      id: 68,
    },
    {
      firstName: "Christopher",
      lastName: "Taylor",
      dateOfBirth: "1987-05-24",
      startDate: "2024-09-15",
      street: "222 Maple Street",
      city: "Miami",
      state: "FL",
      zipCode: "33101",
      department: "HR",
      id: 69,
    },
    {
      firstName: "Ella",
      lastName: "Clark",
      dateOfBirth: "1992-11-07",
      startDate: "2024-10-05",
      street: "333 Elm Avenue",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
      department: "Engineering",
      id: 70,
    },
    {
      firstName: "Isabella",
      lastName: "Wright",
      dateOfBirth: "1995-06-20",
      startDate: "2025-07-10",
      street: "222 Elm Avenue",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
      department: "Engineering",
      id: 71,
    },
    {
      firstName: "Benjamin",
      lastName: "Jackson",
      dateOfBirth: "1990-09-14",
      startDate: "2025-08-15",
      street: "444 Oak Street",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
      department: "Marketing",
      id: 72,
    },
    {
      firstName: "Emily",
      lastName: "Robinson",
      dateOfBirth: "1992-12-30",
      startDate: "2025-09-05",
      street: "666 Pine Avenue",
      city: "San Francisco",
      state: "CA",
      zipCode: "94101",
      department: "Finance",
      id: 73,
    },
    {
      firstName: "William",
      lastName: "Lee",
      dateOfBirth: "1988-11-05",
      startDate: "2025-10-10",
      street: "888 Oak Avenue",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
      department: "HR",
      id: 74,
    },
    {
      firstName: "Victoria",
      lastName: "Hernandez",
      dateOfBirth: "1994-03-17",
      startDate: "2025-11-15",
      street: "999 Elm Street",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
      department: "Engineering",
      id: 75,
    },
    {
      firstName: "James",
      lastName: "Lopez",
      dateOfBirth: "1991-05-23",
      startDate: "2025-12-05",
      street: "111 Pine Street",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
      department: "Marketing",
      id: 76,
    },
    {
      firstName: "Ava",
      lastName: "Gonzalez",
      dateOfBirth: "1993-08-10",
      startDate: "2026-01-10",
      street: "333 Oak Avenue",
      city: "San Francisco",
      state: "CA",
      zipCode: "94101",
      department: "Finance",
      id: 77,
    },
    {
      firstName: "Michael",
      lastName: "Smith",
      dateOfBirth: "1989-07-01",
      startDate: "2026-02-15",
      street: "555 Elm Street",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
      department: "HR",
      id: 78,
    },
    {
      firstName: "Charlotte",
      lastName: "Young",
      dateOfBirth: "1995-04-09",
      startDate: "2026-03-05",
      street: "777 Pine Avenue",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
      department: "Engineering",
      id: 79,
    },
    {
      firstName: "Henry",
      lastName: "Taylor",
      dateOfBirth: "1990-10-15",
      startDate: "2026-04-10",
      street: "999 Oak Avenue",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
      department: "Marketing",
      id: 80,
    },
    {
      firstName: "Mia",
      lastName: "Harris",
      dateOfBirth: "1992-12-05",
      startDate: "2026-05-15",
      street: "111 Elm Street",
      city: "San Francisco",
      state: "CA",
      zipCode: "94101",
      department: "Finance",
      id: 81,
    },
    {
      firstName: "Daniel",
      lastName: "Clark",
      dateOfBirth: "1988-09-20",
      startDate: "2026-06-05",
      street: "333 Pine Avenue",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
      department: "HR",
      id: 82,
    },
    {
      firstName: "Scarlett",
      lastName: "Lewis",
      dateOfBirth: "1994-02-27",
      startDate: "2026-07-10",
      street: "555 Oak Street",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
      department: "Engineering",
      id: 83,
    },
    {
      firstName: "Luke",
      lastName: "Walker",
      dateOfBirth: "1991-06-10",
      startDate: "2026-08-15",
      street: "777 Elm Avenue",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
      department: "Marketing",
      id: 84,
    },
    {
      firstName: "Lily",
      lastName: "Rodriguez",
      dateOfBirth: "1993-09-25",
      startDate: "2026-09-05",
      street: "999 Pine Street",
      city: "San Francisco",
      state: "CA",
      zipCode: "94101",
      department: "Finance",
      id: 85,
    },
    {
      firstName: "Henry",
      lastName: "Wright",
      dateOfBirth: "1989-08-12",
      startDate: "2026-10-10",
      street: "111 Oak Avenue",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
      department: "HR",
      id: 86,
    },
    {
      firstName: "Chloe",
      lastName: "Adams",
      dateOfBirth: "1995-03-20",
      startDate: "2026-11-15",
      street: "222 Elm Street",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
      department: "Engineering",
      id: 87,
    },
    {
      firstName: "Alexander",
      lastName: "Cook",
      dateOfBirth: "1990-07-02",
      startDate: "2026-12-05",
      street: "444 Pine Avenue",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
      department: "Marketing",
      id: 88,
    },
    {
      firstName: "Grace",
      lastName: "Bailey",
      dateOfBirth: "1992-10-10",
      startDate: "2027-01-10",
      street: "666 Oak Street",
      city: "San Francisco",
      state: "CA",
      zipCode: "94101",
      department: "Finance",
      id: 89,
    },
    {
      firstName: "Joseph",
      lastName: "Russell",
      dateOfBirth: "1988-09-18",
      startDate: "2027-02-15",
      street: "888 Elm Avenue",
      city: "Dallas",
      state: "TX",
      zipCode: "75201",
      department: "HR",
      id: 90,
    },
  ],
};

/**
 * The Redux slice for managing employees.
 * @type {import("@reduxjs/toolkit").Slice}
 */
export const employeeSlice = createSlice({
  //createSlice
  //A function that accepts an initial state, an object of reducer functions, and a "slice name", and automatically generates action creators and action types that correspond to the reducers and state.
  name: "employee",
  initialState,
  reducers: {
    // Redux reducer functions for managing employees
    addEmployee(state, { payload }) {
      state.employees.push(payload.employee);
    },
  },
});

export const { addEmployee } = employeeSlice.actions;

export default employeeSlice.reducer;
